//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ASP.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH
    {
        public string C_email_ID { get; set; }
        public string password { get; set; }
        public string powers { get; set; }
    
        public virtual INFORMATION INFORMATION { get; set; }
    }
}
