//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ASP.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.BILLs = new HashSet<BILL>();
            this.CARTs = new HashSet<CART>();
        }
    
        public string C_id { get; set; }
        public string nameBook { get; set; }
        public double priceBook { get; set; }
        public string contentBook { get; set; }
        public int countBook { get; set; }
        public string imgBook_ID { get; set; }
        public string categoryBook_ID { get; set; }
        public string discountBook_ID { get; set; }
        public string publishingHouseBook_ID { get; set; }
        public string author_id { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual DISCOUNT_BOOK DISCOUNT_BOOK { get; set; }
        public virtual IMAGE_BOOK IMAGE_BOOK { get; set; }
        public virtual PUBLISHING_HOUSE PUBLISHING_HOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual IMPORT_BOOK IMPORT_BOOK { get; set; }
    }
}
