//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ASP.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.INFORMATION = new HashSet<INFORMATION>();
            this.AUTHORs = new HashSet<AUTHOR>();
        }
    
        public string C_id { get; set; }
        public string nameBook { get; set; }
        public Nullable<double> priceBook { get; set; }
        public string contentBook { get; set; }
        public Nullable<int> countBook { get; set; }
        public string imgBook_ID { get; set; }
        public string categoryBook_ID { get; set; }
        public string discountBook_ID { get; set; }
        public string publishingHouseBook_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual DISCOUNT_BOOK DISCOUNT_BOOK { get; set; }
        public virtual PUBLISHING_HOUSE PUBLISHING_HOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMATION> INFORMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHOR> AUTHORs { get; set; }
    }
}
