//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ASP.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_BOOK
    {
        public string book_ID { get; set; }
        public System.DateTime import_date { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
